package autogenerated.type;


import tv.twitch.android.mod.bridges.Hooks;


public class PlaybackAccessTokenParams$1 {
    public void marshal(Object inputFieldWriter) {
        String res = Hooks.hookPlaybackAccessPlayerType("bla-bla"); // TODO: __HOOK_PARAM
        if (Hooks.isSurestreamAdblockV2On())
            ;
    }
}
